apiVersion: v1
kind: Service
metadata:
  name: myserver
  namespace: default
  label:
    app: myserver
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: web
  type: LoadBalancer
